### ISSUE TITLE
中文用户的反馈

### ISSUE THREAD

**Issue by chaowise** [notable/notable#1092]
1，新建笔记默认是标题，这个不太喜欢，因为大部分笔记都是文本，没必要设置标题。建议可以自定义设置。
2，打开软件默认连接GitHub，你懂的，中国连不上，导致每次打开软件都提示需要手动更新，看着烦。也希望能够设置不自动更新。

**Comment by fabiospampinato** [comment]
This repo is in english, and I don't speak chinese, please use translation software in the future. 

According to what Google makes of that:

> 1. The default for new notes is the title. This is not a favorite because most notes are text, so there is no need to set a title. It is recommended that you can customize the settings.

The title is used for naming notes in the file system, and displaying them in the notes list, amongst other places. I don't think removing it makes sense.

I could make the default title customizable, but as the app overall is English-only right now would that really be useful? Besides whatever title you might want to use as a default instead will most probably be changed right away anyway.

> 2. Open the software and connect to GitHub by default. You know, China ca n’t connect. As a result, every time you open the software, you are prompted to manually update it.

This should be fixed in the upcoming v1.9, the app will check for updates by querying [download.notable.md/version](https://download.notable.md/version) too. Can you access that from China?

The bundles are stored on GitHub only though, it would be a bit impractical to host them somewhere else too in the short term, but maybe I can make a built-in proxy for that 🤔 What's the standard solution for this sorts of issues in China?

> I also want to be able to set it to not update automatically.

Duplicate of #612

**Comment by chaowise** [comment]
Thank you for your reply.
Update as long as you set up the software without starting it.
I still have a way to log in to GitHub, but it just takes time.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fabio Spampinato"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 晚上11:17
收件人: "notable/notable"<notable@noreply.github.com&gt;; 
抄送: "1039251539"<chaowise@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [notable/notable] 中文用户的反馈 (#1092)





 
This repo is in english, and I don't speak chinese, please use translation software in the future.
 
According to what Google makes of that:
   
The default for new notes is the title. This is not a favorite because most notes are text, so there is no need to set a title. It is recommended that you can customize the settings.
   
The title is used for naming notes in the file system, and displaying them in the notes list, amongst other places. I don't think removing it makes sense.
 
I could make the default title customizable, but as the app overall is English-only right now would that really be useful? Besides whatever title you might want to use as a default instead will most probably be changed right away anyway.
   
Open the software and connect to GitHub by default. You know, China ca n’t connect. As a result, every time you open the software, you are prompted to manually update it.
   
This should be fixed in the upcoming v1.9, the app will check for updates by querying download.notable.md/version too. Can you access that from China?
 
The bundles are stored on GitHub only though, it would be a bit impractical to host them somewhere else too in the short term, but maybe I can make a built-in proxy for that  What's the standard solution for this sorts of issues in China?
  
I also want to be able to set it to not update automatically.
  
Duplicate of #612

**Comment by fabiospampinato** [comment]
> I still have a way to log in to GitHub, but it just takes time.

What other solution would you prefer? Like what would you like me to do?

**Comment by PhoenixZeng** [comment]
Then. How about multilingual support?

**Comment by fabiospampinato** [comment]
@PhoenixZeng We are tracking that here: #126, at some point it will happen but right now it's not a priority.

If you have any other suggestions I'm all ears. Like would you like the app to have settings for setting a proxy? Should I host updates somewhere else? I'm not really familiar with how to handle this.

**Comment by PhoenixZeng** [comment]
As also a Chinese user .
I think do not auto check update when open this program is enough.
U can just check update by hand 
proxy and useless 
about `host updates`  I don't have useful suggestions . 
maybe update to Win10 store? or DevOps on MS azure ?  Whatever, but that's another question
