### ISSUE TITLE
Evernote enex import doesn't include images in the note

### ISSUE THREAD

**Issue by crumbletop** [notable/notable#1343]
- **OS Version**:  MacOS 10.13.6
- **Notable Version**: 1.8.4

### Current behavior

Import enex file with images.  File contains only the text portions of the note and includes images as attachments only. Additionally, the import contains 2 attachments for each image it imports.  One uses the hash as the name ([hash].jpeg) and the other uses the proper file name ([image name].jpg).

Steps to reproduce:  
1) Import enex file into Notable.
2) Observe that the images were imported as attachments, but are not displayed in the resulting note and not listed in the md file.
3) observe that the number of images in the orginal note is 2 and the number of attachments is 4 (2 of each image).

### Expected behavior

Notes that include images as a part of the note should still include the images when imported to Notable.  The md file should include the image _in line_ with the note text.  I have included a zip file of a sample enex, a "Notable as Imported" md of the sample, and a "Notable Suggested" md of what the import should achieve. 

I shrunk the original images in the zip file to accommodate
[enex with images example.zip](https://github.com/notable/notable/files/5397528/enex.with.images.example.zip)
 github size limits.

**Comment by fabiospampinato** [comment]
I'll take a closer look at this, but I think there's a chance this may have been fixed already, I'm not sure though and I'm not sure if the hypothetical fix shipped in the latest alpha yet, could you check if v1.9 alpha 19 has this issue? https://github.com/notable/notable-experimental/releases

**Comment by crumbletop** [comment]
I downloaded the latest alpha (1.9 alpha 19) and tried the importer.  It doesn’t handle images as links that are visible in-line.  It also duplicates all attachments - one with the correct filename, and the other with a hash as the name.  So the problem is still present.

On Oct 20, 2020, at 8:24 PM, Fabio Spampinato <notifications@github.com<mailto:notifications@github.com>> wrote:



I'll take a closer look at this, but I think there's a chance this may have been fixed already, I'm not sure though and I'm not sure if the hypothetical fix shipped in the latest alpha yet, could you check if v1.9 alpha 19 has this issue? https://github.com/notable/notable-experimental/releases

**Comment by rgrajan** [comment]
I am able to reproduce this issue in Windows 10, Notable 1.8.4
