### ISSUE TITLE
Reveal in Folder issue

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#580]
1.3 and 1.4.0 in Windows 10 ...

I have never been able to get _Reveal in Folder_ to work. It doesn't seem to do anything.

**Comment by Armagedoom** [comment]
It works properly in my windows 10 and in my job computer with Windows 10.
@jeff9315 , If you could try it in another machine with windows 10 / try to give specifics on what should I check in mine to try and have a closer look on the issue, that would be great.

**Comment by jeff9315** [comment]
Since @fabiospampinato  marked it as a bug and for the Next Milestone, I assume he was able to duplicate it.

**Comment by fabiospampinato** [comment]
@jeff9315 Actually I wasn't, I just assumed that you were actually seeing this bug.

**Comment by Armagedoom** [comment]
I found a related bug while developing the popover for attachments #616.
Seems like "this.attachment" is not properly being updated on note change.
How to reproduce:
* Load a note with attachments. Right-click any of them, then use "reveal in folder" or "copy file name" (#616)
* The first time it works properly
* Change the note to another note with another different attachment
* Now use the context menu for anything, you will get the FIRST attachment (Either reveal its folder or copy file name). Do it again with other notes, you will still get the FIRST attachment you used.

Please let me know if you need more information on how to reproduce.

**Comment by Armagedoom** [comment]
Found and fixed the issue: https://github.com/notable/notable/pull/622

**Comment by fabiospampinato** [comment]
@Armagedoom I can reproduce the issue, thanks a lot for reporting it 👍

**Comment by fabiospampinato** [comment]
The issue reported by @Armagedoom has been worked around [here](https://github.com/notable/notable/commit/9c72c624546d3f45c55f51fc562393becde22631).

The original issue reported by @jeff9315 I can't reproduce, I just tried v1.4 under Windows 10 and it works as expected. I'll keep this open to track how many users are affected by this, if anybody can help me reproduce this it would be great. 

@jeff9315 the next version will use Electron v5, perhaps this is caused by some weird bug that got fixed in v5, it'd be useful if you tried the next version when that's released to check if you can still reproduce this bug.

**Comment by jeff9315** [comment]
These still don't work in Notable 1.5 on Win 10:
- Reveal In Folder
- Check for Updates
- Open Data Directory

If no one else reports it, it probably has to do with my setup.

**Comment by Armagedoom** [comment]
> These still don't work in Notable 1.5 on Win 10

I suggest you try running the following command in a "CMD" of windows (Win+R -> cmd -> there):

explorer "c:"
explorer

And play with that.

All of the options work in my tests. Also, the issue I reported was fixed with the workaround, so I would call this issue as fixed / unable to be reproduced.

**Comment by fabiospampinato** [comment]
>  Also, the issue I reported was fixed with the workaround, so I would call this issue as fixed / unable to be reproduced.

I considered the issue you reported as a separate issue. Since @jeff9315 is still experiencing the original issue for some reason I don't think this should be closed, even I can't currently reproduce it.

**Comment by fabiospampinato** [comment]
@jeff9315 Is this still not working for you in v1.8.2? We are using Electron 7 now, hopefully they fixed this at some point.

**Comment by jeff9315** [comment]
Is working.
